### ISSUE TITLE
NoSuchMethodError - plugin needs to be updated

### ISSUE THREAD

**Issue by don-vip** [gidema/josm-ods-bag#18]
See https://josm.openstreetmap.de/ticket/13954 plugin needs to be updated to latest JOSM API.

**Comment by gidema** [comment]
Thanks for moving this issue from the Josm tickets to here. The bug actually is in the OpenDataServices plug-in (https://github.com/gidema/josm-openservices), but these plug-ins are closely related.
There was another incompatibility with Josm 11223 that will be fixed in the 0.6.9.
I'm currently testing the updated plug-in.

**Comment by gidema** [comment]
Fixed in version 0.6.9
